config/routes.rb
Rails.application.routes.draw do
  root to: 'home#top'

  devise_for :users, controllers: {
    # registrationsコントローラーを編集できるようにする
    registrations: 'users/registrations'
  }
  devise_scope :user do
    # 管理画面を認識させるため、createはページが存在しないため必要無し
    get 'admin/users/new' => 'users/registrations#new', as: :new_user_admin_registration
    # 管理者用編集パス
    get 'admin/users/:id/edit' => 'users/registrations#edit', as: :edit_other_user_registration
    match 'admin/users/:id', to: 'users/registrations#update', via: [:patch, :put], as: :other_user_registration
  end

  resources :leads do
    collection do
      get 'all_leads'
      get 'my_leads'
      get 'csv'
      post 'csv_import'
    end
    member do
      patch 'update_sales_process'
    end
    resources :activities do
      collection do
        get 'search'
      end
    end
    resources :schedules
    resources :losts
    resources :images
  end

  resources :lead_seminars do
    member do
      patch 'update_attend'
      patch 'update_approval'
      get 'edit_reason'
    end
  end

  resources :activities do
    collection do
      get 'all_meetings'
      get 'my_meetings'
      get 'all_orders'
      get 'my_orders'
    end
  end

  resources :losts do
    collection do
      get 'all_losts'
      get 'my_losts'
    end
  end

  resources :schedules, only: [:index]

  resources :seminars
  resources :sources
  resources :sales_processes
  resources :properties do
    resources :rooms
  end
  resources :losts, only: [:index]
  resources :notifications, only: [:index]
  
  resource :admin, only: [:show] do
    resources :template_models
    resources :hides
    resources :users, :only => [:index, :show]
  end
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :lead
  belongs_to :creator, class_name: 'User'
  belongs_to :attender, class_name: 'User', optional: true

  with_options presence: true do
    validates :title
    validates :description
    validates :schedule_date_time
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: [:edit, :update, :destroy]
  before_action :set_lead, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_beginning_of_week

  def index
    @schedules = Schedule.all
  end

  def new
    @schedule = Schedule.new
  end

  def create
    @schedule = @lead.schedules.new(schedule_params)
    @schedules = @lead.schedules
    if @schedule.save
      flash.now[:notice] = '予定が作成されました。'
    else
      flash.now[:alert] = '予定の作成に失敗しました'
    end
  end

  def edit
  end

  def update
    @schedules = @lead.schedules
    if @schedule.update(schedule_params)
      flash.now[:notice] = '予定が更新されました'
    else
      flash.now[:alert] = '予定の更新に失敗しました'
    end
  end

  def destroy
    if @schedule.destroy
      @schedules = @lead.schedules
      flash.now[:notice] = '予定が削除されました'
    else
      flash.now[:alert] = '予定の削除に失敗しました'
    end
  end

  private

  def set_schedule
    @schedule = Schedule.find(params[:id])
  end

  def set_lead
    @lead = Lead.find(params[:lead_id])
  end

  def set_beginning_of_week
    Date.beginning_of_week = :sunday
  end

  def schedule_params
    params.require(:schedule).permit(
      :title,
      :description,
      :schedule_date_time,
      :attender_id 
    ).merge(creator_id: current_user.id)
  end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_detail.html.erb
<div class="d-flex">
  <!-- トグルアイコン -->
  <div class="ps-2 pe-3">
    <i class="fa-solid fa-chevron-right schedule-toggle-icon cursor-pointer text-dark" data-schedule-toggle-icon="<%= schedule.id %>"></i>
  </div>
  <div class="w-100">
    <!-- ヘッダー -->
    <div class="d-flex justify-content-between align-items-center">
      <!-- 左 -->
      <div>
        <h6>予定</h6>
        <span class="fs-7"><%= schedule.creator.name %>さんが予定を作成しました</span>
      </div>
      <!-- 右 -->
      <div class="d-flex gap-1">
        <div>
          <span class="fs-7"><%= l schedule.created_at %></span>
        </div>
        <!-- ボタン -->
        <div class="dropdown d-flex justify-content-end">
          <button class="bg-transparent border-0" type="button" id="dropdownMenuButton" data-mdb-toggle="dropdown" aria-expanded="false">
            <i class="fa-solid fa-ellipsis-vertical rounded-circle text-hover d-flex align-items-center justify-content-center" style="width: 30px; height: 30px;"></i>
          </button>
          <ul class="dropdown-menu border" aria-labelledby="dropdownMenuButton">
            <li>
              <%= link_to "編集", edit_lead_schedule_path(schedule.lead, schedule), remote: true, class: "dropdown-item" %>
            </li>
            <li>
              <%= link_to "削除", lead_schedule_path(schedule.lead, schedule), method: :delete, remote: true, class: "dropdown-item", data: { confirm: '削除しますか？' } %>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <%# トグルコンテンツ %>
    <div data-schedule-toggle-content="<%= schedule.id %>", style="display: none;">
      <!-- ボディー -->
      <div class="pt-2 d-flex flex-column gap-1">
        
        <div>
          <span class="font-weight-bold fs-8">件名</span>
          <div>
            <span class="fs-9"><%= schedule.title %></span>
          </div>
        </div>

        <div>
          <span class="font-weight-bold fs-8">予定日時</span>
          <div>
            <span class="fs-9"><%= l schedule.schedule_date_time %></span>
          </div>
        </div>

        <div>
          <span class="font-weight-bold fs-8">同席者</span>
          <div>
            <span class="fs-9"><%= schedule.attender&.name %></span>
          </div>
        </div>

        <div>
          <span class="font-weight-bold fs-8">説明</span>
          <div class="border rounded-3 p-1">
            <span class="fs-8"><%= safe_join(schedule.description.split("\n"),tag(:br)) %></span>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/schedules/_form.html.erb
<% if schedule.new_record? %>
  <h6 class="pb-2">予定作成</h6>
<% else %>
  <h6 class="pb-2">予定編集</h6>
<% end %>

<%= form_with model: [lead, schedule] do |f| %>
  <div class="py-3 d-flex flex-column gap-3" style="border-top: 1px dashed #d3d6de; border-bottom: 1px dashed #d3d6de;">
    <%# エラーメッセージ %>
    <%= render 'layouts/error_messages', model: f.object %>

    <div>
      <%= f.label :title, '件名' %><span class="text-danger">*</span>
      <%= f.text_field :title, class: "form-control" %>
    </div>

    <div>
      <%= f.label :schedule_date_time, '予定日時' %><span class="text-danger">*</span>
      <%= f.datetime_field :schedule_date_time, include_blank: true, class: "form-control w-auto" %>
    </div>

    <div>
      <%= f.label :attender_id, '同席者' %>
      <%= f.collection_select :attender_id, User.all, :id, :name, {include_blank: "---"}, {class: "form-control w-auto"} %>
    </div>

    <div>
      <%= f.label :description, '説明' %><span class="text-danger">*</span>
      <%= f.text_area :description, placeholder: "説明", class: "form-control mh-100p" %>
    </div>

  </div>
  <div class="pt-3 d-flex justify-content-end gap-2">
    <button type="button" class="btn btn-light close-schedule-form" data-mdb-ripple-color="dark">閉じる</button>
    <% if schedule.new_record? %>
      <%= f.submit "作成", class: "btn btn-primary" %>
    <% else %>
      <%= f.submit "更新", class: "btn btn-primary" %>
    <% end %>
  </div>
<% end %>

app/views/schedules/_no_schedule.html.erb
<% if schedules.empty? %>
  予定がありません
<% end %>

app/views/schedules/_show.html.erb
<div class="schedule-card p-2 border rounded-3 position-relative" data-schedule="<%= schedule.id %>">
  <%= render partial: 'schedules/detail', locals: { schedule: schedule } %>
</div>

app/views/schedules/_tab.html.erb
<!-- 作成ボタン -->
<div class="p-2">
  <%= link_to "新規作成", new_lead_schedule_path(lead), remote: true, class: "btn btn-primary" %>
</div>
<div class="p-2 d-flex flex-column gap-4">
  <!-- フォーム -->
  <div id="scheduleFormWrap" class="schedule-form-wrap p-3 border rounded-3" style="display: none;">
  </div>
  <div id="schedules" class="d-flex flex-column gap-1">
    <% schedules.each do |schedule|%>
      <%= render partial: 'schedules/show', locals: { schedule: schedule } %>
    <% end %>
    <div id="noSchedule" class="py-5 text-center">
      <%= render partial: 'schedules/no_schedule', locals: { schedules: schedules } %>
    </div>
  </div>
</div>

app/views/schedules/create.js.erb
<%# エラーがあったときの処理 %>
<% if @schedule.errors.present? %>
  <%# フォームのレンダリング %>
  $("#scheduleFormWrap").html("<%= j(render partial: 'schedules/form', locals: { lead: @lead, schedule: @schedule }) %>");

<%# エラーが無いときの処理 %>
<% else %>
  <%# フォームを非表示 %>
  $(".schedule-form-wrap").hide();

  <%# 要素を追加 %>
  $("#schedules").prepend("<%= j(render partial: 'schedules/show', locals: { schedule: @schedule }) %>");

  <%# アクティブを追加 %>
  $('[data-schedule="<%= @schedule.id %>"]').addClass("is-active");

  <%# アクティブを削除 %>
  setTimeout(function() {
    $('[data-schedule="<%= @schedule.id %>"]').removeClass("is-active");
  }, 5000);

  <%# noScheduleをレンダリング %>
  $("#noSchedule").html("<%= j(render partial: 'schedules/no_schedule', locals: { schedules: @schedules }) %>");
<% end %>

<%# フラッシュの表示 %>
$("#flash").html("<%= j(render 'layouts/flash') %>");

app/views/schedules/destroy.js.erb
<%# 要素を削除 %>
$(`[data-schedule=<%= @schedule.id %>]`).fadeOut('fast').queue(function() {
  $(`[data-schedule=<%= @schedule.id %>]`).remove();
});

<%# フォームが開いていてインスタンスが同じならフォームを閉じる %>
if ($('#scheduleFormWrap').css('display') == 'block') {
  let action = $('#scheduleFormWrap form').attr('action');
  let path = "<%= lead_schedule_path(@lead, @schedule) %>";
  if(action == path) {
    $(".schedule-form-wrap").hide();
  }
}

<%# noScheduleをレンダリング %>
$("#noSchedule").html("<%= j(render partial: 'schedules/no_schedule', locals: { schedules: @schedules }) %>");

<%# フラッシュの表示 %>
$("#flash").html("<%= j(render 'layouts/flash') %>");

app/views/schedules/edit.js.erb
<%# フォームを全てリセット %>
$(".schedule-form-wrap").hide();

<%# 編集中を全てリセット %>
$(".schedule-card").removeClass("is-edit");

<%# 編集中を追加 %>
$('[data-schedule="<%= @schedule.id %>"]').addClass("is-edit");

<%# フォームの表示とレンダリング %>
$("#scheduleFormWrap").html("<%= j(render partial: 'schedules/form', locals: { lead: @lead, schedule: @schedule }) %>");
$("#scheduleFormWrap").slideDown();

<%# トグルの開閉状態で分岐 %>
if($(`[data-toggle-icon=<%= @schedule.id %>]`).hasClass("is-open")) {
  <%# 更新部分をレンダリング %>
  $(`[data-schedule=<%= @schedule.id %>]`).html("<%= j(render partial: 'schedules/detail', locals: { schedule: @schedule }) %>");
  <%# トグルを開く %>
  $(`[data-toggle-icon=<%= @schedule.id %>]`).addClass("is-open");
  $(`[data-toggle-content=<%= @schedule.id %>]`).show();
} else {
  <%# 更新部分をレンダリング %>
  $(`[data-schedule=<%= @schedule.id %>]`).html("<%= j(render partial: 'schedules/detail', locals: { schedule: @schedule }) %>");
}

app/views/schedules/index.html.erb
<main>
  <div class="content-wrap content-wrap--table content-wrap--height">
    <div>
      <!-- ヘッダー -->
      <div class="p-3 d-flex justify-content-between">
        <!-- 左 -->
        <div class="d-flex flex-column justify-content-between">
          <!-- 上段 -->
          <div class="main-heading">
            <i class="fa-solid fa-calendar-days fa-lg main-heading--box"></i>
            <h6 class="main-heading--title">カレンダー</h6>
          </div>
          <!-- 下段 -->
          <div class="d-flex justify-content-between">
          </div>
        </div>
        <!-- 右 -->
        <div class="d-flex flex-column justify-content-between">
          <!-- 上段 -->
          <div class="d-flex gap-1">
          </div>
          <!-- 下段 -->
          <div class="d-flex justify-content-end gap-2">
          </div>
        </div>
      </div>
      <!-- テーブル -->
      <div class="px-3">
        <%= month_calendar do |date| %>
          <div class="text-center text-body font-weight-bold fs-8">
            <%= date.day %>
          </div>
          <div class="pt-2 d-flex flex-column gap-1">
            <!-- セミナー -->
            <% @seminars = Seminar.where(start_date_time: date.in_time_zone.all_day) %>
            <% @seminars.each do |seminar| %>
              <%= link_to seminar_path(seminar), class: "text-hover ps-1 rounded-3" do %>
                <i class="fa-solid fa-circle text-warning fs-7 pe-1"></i>
                <span class="text-body fs-9">
                  <%= l seminar.start_date_time, format: :short_time %> セミナー
                </span>
              <% end %>
            <% end %>
            <!-- スケジュール -->
            <% if admin? %>
              <% @schedules = Schedule.where(schedule_date_time: date.in_time_zone.all_day) %>
            <% else %>
              <% @schedules = Schedule.where(schedule_date_time: date.in_time_zone.all_day, creator_id: current_user.id).or(Schedule.where(schedule_date_time: date.in_time_zone.all_day, attender_id: current_user.id)) %>
            <% end %>
            <% @schedules.each do |schedule| %>
              <%= link_to lead_path(schedule.lead), class: "text-hover ps-1 rounded-3" do %>
                <i class="fa-solid fa-circle text-success fs-7 pe-1"></i>
                <span class="text-body fs-9">
                  <%= l schedule.schedule_date_time, format: :short_time %> <%= schedule.title.truncate(13) %>
                </span>
              <% end %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/schedules/new.js.erb
<%# フォームを全てリセット %>
$(".schedule-form-wrap").hide();

<%# フォームのレンダリングと表示 %>
$("#scheduleFormWrap").html("<%= j(render partial: 'schedules/form', locals: { lead: @lead, schedule: @schedule }) %>");
$("#scheduleFormWrap").slideDown();

app/views/schedules/update.js.erb
<%# フォームレンダリング %>
$('[data-schedule-form="' + <%= @schedule.id %> + '"]').empty();
$('[data-schedule-form="' + <%= @schedule.id %> + '"]').append(
  "<%= j(
    render 'schedules/form',
    lead: @lead,
    schedule: @schedule
  ) %>"
);

<%# エラーがあったときの処理 %>
<% if @schedule.errors.present? %>
  <%# フォームのレンダリング %>
  $("#scheduleFormWrap").html("<%= j(render partial: 'schedules/form', locals: { lead: @lead, schedule: @schedule }) %>");

<%# エラーが無いときの処理 %>
<% else %>
  <%# フォームを非表示 %>
  $(".schedule-form-wrap").hide();

  <%# 編集中を全てリセット %>
  $(".schedule-card").removeClass("is-edit");

  <%# アクティブを追加 %>
  $('[data-schedule="<%= @schedule.id %>"]').addClass("is-active");

  <%# アクティブを削除 %>
  setTimeout(function() {
    $('[data-schedule="<%= @schedule.id %>"]').removeClass("is-active");
  }, 5000);

  <%# noScheduleをレンダリング %>
  $("#noSchedule").html("<%= j(render partial: 'schedules/no_schedule', locals: { schedules: @schedules }) %>");

  <%# トグルの開閉状態で分岐 %>
  if($(`[data-schedule-toggle-icon=<%= @schedule.id %>]`).hasClass("is-open")) {
    <%# 更新部分をレンダリング %>
    $(`[data-schedule=<%= @schedule.id %>]`).html("<%= j(render partial: 'schedules/detail', locals: { schedule: @schedule }) %>");
    <%# トグルを開く %>
    $(`[data-schedule-toggle-icon=<%= @schedule.id %>]`).addClass("is-open");
    $(`[data-schedule-toggle-content=<%= @schedule.id %>]`).show();
  } else {
    <%# 更新部分をレンダリング %>
    $(`[data-schedule=<%= @schedule.id %>]`).html("<%= j(render partial: 'schedules/detail', locals: { schedule: @schedule }) %>");
  }
<% end %>

<%# フラッシュの表示 %>
$("#flash").html("<%= j(render 'layouts/flash') %>");