config/routes.rb
Rails.application.routes.draw do
  root to: 'home#top'

  devise_for :users, controllers: {
    # registrationsコントローラーを編集できるようにする
    registrations: 'users/registrations'
  }
  devise_scope :user do
    # 管理画面を認識させるため、createはページが存在しないため必要無し
    get 'admin/users/new' => 'users/registrations#new', as: :new_user_admin_registration
    # 管理者用編集パス
    get 'admin/users/:id/edit' => 'users/registrations#edit', as: :edit_other_user_registration
    match 'admin/users/:id', to: 'users/registrations#update', via: [:patch, :put], as: :other_user_registration
  end

  resources :leads do
    collection do
      get 'all_leads'
      get 'my_leads'
      get 'csv'
      post 'csv_import'
    end
    member do
      patch 'update_sales_process'
    end
    resources :activities do
      collection do
        get 'search'
      end
    end
    resources :schedules
    resources :losts
    resources :images
  end

  resources :lead_seminars do
    member do
      patch 'update_attend'
      patch 'update_approval'
      get 'edit_reason'
    end
  end

  resources :activities do
    collection do
      get 'all_meetings'
      get 'my_meetings'
      get 'all_orders'
      get 'my_orders'
    end
  end

  resources :losts do
    collection do
      get 'all_losts'
      get 'my_losts'
    end
  end

  resources :schedules, only: [:index]

  resources :seminars
  resources :sources
  resources :sales_processes
  resources :properties do
    resources :rooms
  end
  resources :losts, only: [:index]
  resources :notifications, only: [:index]
  
  resource :admin, only: [:show] do
    resources :template_models
    resources :hides
    resources :users, :only => [:index, :show]
  end
end

app/models/hide.rb
class Hide < ApplicationRecord
  belongs_to :lead

  with_options presence: true do
    validates :reason
  end
end

app/controllers/hides_controller.rb
class HidesController < ApplicationController
  before_action :set_hide, only: [:show, :edit, :update, :destroy]

  def index
    @hides = Hide.all
  end
  
  def show
  end

  def new
    @hide = Hide.new
  end

  def create
    @hide = Hide.new(hide_params)
    if @hide.save
      redirect_to admin_hide_path(@hide), notice: "非表示が作成されました"
    else
      flash.now[:alert] = '非表示の作成に失敗しました'
      render :new
    end
  end

  def edit
  end

  def update
    if @hide.update(hide_params)
      redirect_to admin_hide_path(@hide), notice: "非表示が更新されました"
    else
      flash.now[:alert] = '非表示の更新に失敗しました'
      render :edit
    end
  end
  
  def destroy
    if @hide.destroy
      redirect_to admin_hides_path, notice: "非表示が削除されました"
    else
      redirect_to admin_hide_path(hide), alert: "非表示の削除に失敗しました"
    end
  end

  private
  def set_hide
    @hide = Hide.find(params[:id])
  end
  
  def hide_params
    params.require(:hide).permit(
      :reason,
      :lead_id
    )
  end
end

app/helpers/hides_helper.rb
module HidesHelper
end

app/views/hides/_form.html.erb
<% url = hide.new_record? ? admin_hides_path : admin_hide_path(hide) %>

<%= form_with model: hide, url: url, local: true do |f| %>
  <div class="content-wrap w-60 mx-auto">
    <div class="w-50 mx-auto py-5">
      <div class="d-flex flex-column gap-4">
        <!-- エラーメッセージ -->
        <%= render 'layouts/error_messages', model: f.object %>

        <div>
          <%= f.label :lead_id, "リード", class: "form-label font-weight-bold" %><span class="text-danger">【必須】</span>
          <div class="d-flex">
          <%= f.collection_select :lead_id, Lead.all, :id, :name, { prompt: "---" }, {class: "select-hide form-control w-100"} %>
          </div>
        </div>

        <div>
          <%= f.label :reason, "理由", class: "form-label font-weight-bold" %><span class="text-danger">【必須】</span>
          <%= f.text_area :reason, placeholder: "理由", class: "form-control mh-100p" %>
        </div>

      </div>
    </div>
  </div>
  <!-- ボタン -->
  <div class="text-center pt-4">
    <% if hide.new_record? %>
      <%= f.submit "作成", class: "btn btn-primary btn-rounded btn-lg px-5" %>
    <% else %>
      <%= f.submit "更新", class: "btn btn-primary btn-rounded btn-lg px-5" %>
    <% end %>
  </div>
<% end %>

app/views/hides/_index_table.html.erb
<table class="index-table-2">
  <!-- ヘッダー -->
  <tr>
    <th>リード</th>
    <th>理由</th>
  </tr>
  <!-- ボディー -->
  <% hides.each do |hide| %>
    <tr>
      <td>
        <%= link_to hide.lead.name, admin_hide_path(hide) %>
      </td>
      <td>
        <%= hide.reason.truncate(30) %>
      </td>
    </tr>
  <% end %>
</table>

app/views/hides/edit.html.erb
<main class="pt-0">
  <!-- ナビゲーター -->
  <div class="position-absolute pt-3">
    <%= link_to admin_hide_path(@hide), class: "" do %>
      <i class="fa-solid fa-chevron-left"></i> 戻る
    <% end %>
  </div>
  <!-- ヘッダー -->
  <h4 class="text-center py-4">非表示を編集</h4>
  <!-- フォーム -->
  <%= render partial: 'form', locals: { hide: @hide } %>
</main>

app/views/hides/index.html.erb
<main>
  <div class="content-wrap content-wrap--table content-wrap--height">
    <div>
      <!-- ヘッダー -->
      <div class="p-3 d-flex justify-content-between">
        <!-- 左 -->
        <div class="d-flex flex-column justify-content-between gap-4">
          <!-- 上段 -->
          <div class="main-heading">
            <i class="fa-solid fa-file-lines fa-lg main-heading--box"></i>
            <h6 class="main-heading--title">非表示</h6>
          </div>
          <!-- 下段 -->
          <div class="d-flex justify-content-between">
          </div>
        </div>
        <!-- 右 -->
        <div class="d-flex flex-column justify-content-between">
          <!-- 上段 -->
          <div class="d-flex gap-1">
            <%= link_to "新規登録", new_admin_hide_path, class: "btn btn-primary btn-rounded" %>
          </div>
          <!-- 下段 -->
          <div class="d-flex justify-content-end gap-2">
          </div>
        </div>
      </div>
      <!-- テーブル -->
      <div class="table-wrapper">
        <%= render partial: 'index_table', locals: { hides: @hides } %>
      </div>
    </div>
  </div>
</main>

app/views/hides/new.html.erb
<main class="pt-0">
  <!-- ナビゲーター -->
  <div class="position-absolute pt-3">
    <%= link_to admin_hides_path, class: "" do %>
      <i class="fa-solid fa-chevron-left"></i> 戻る
    <% end %>
  </div>
  <!-- ヘッダー -->
  <h4 class="text-center py-4">非表示を登録</h4>
  <!-- フォーム -->
  <%= render partial: 'form', locals: { hide: @hide } %>
</main>

app/views/hides/show.html.erb
<main class="pt-0">
  <!-- ナビゲーター -->
  <div class="position-absolute pt-3">
    <%= link_to admin_hides_path, class: "" do %>
      <i class="fa-solid fa-chevron-left"></i> 一覧
    <% end %>
  </div>
  <!-- ヘッダー -->
  <h4 class="text-center py-4">非表示詳細</h4>
  <!-- ボディー -->
  <div class="content-wrap w-60 mx-auto py-4">
    <div class="w-50 mx-auto d-flex flex-column gap-3">
    
      <div>
        <span class="box-heading pb-2">リード</span>
        <span><%= @hide.lead.name %></span>
      </div>

      <div>
        <span class="box-heading pb-2">理由</span>
        <span><%= safe_join(@hide.reason.split("\n"),tag(:br)) %></span>
      </div>

    </div>
  </div>
  <!-- ボタン -->
  <% if admin? %>
    <div class="pt-4 d-flex justify-content-center gap-3">
      <%= link_to "編集", edit_admin_hide_path(@hide), class: "btn btn-primary btn-rounded btn-lg px-5" %>
      <%= link_to "登録解除", admin_hide_path(@hide), method: :delete, class: "btn btn-danger btn-rounded btn-lg px-5", data: { confirm: '削除しますか？' } %>
    </div>
  <% end %>
</main>