config/routes.rb
Rails.application.routes.draw do
  root to: 'home#top'

  devise_for :users, controllers: {
    # registrationsコントローラーを編集できるようにする
    registrations: 'users/registrations'
  }
  devise_scope :user do
    # 管理画面を認識させるため、createはページが存在しないため必要無し
    get 'admin/users/new' => 'users/registrations#new', as: :new_user_admin_registration
    # 管理者用編集パス
    get 'admin/users/:id/edit' => 'users/registrations#edit', as: :edit_other_user_registration
    match 'admin/users/:id', to: 'users/registrations#update', via: [:patch, :put], as: :other_user_registration
  end

  resources :leads do
    collection do
      get 'all_leads'
      get 'my_leads'
      get 'csv'
      post 'csv_import'
    end
    member do
      patch 'update_sales_process'
    end
    resources :activities do
      collection do
        get 'search'
      end
    end
    resources :schedules
    resources :losts
    resources :images
  end

  resources :lead_seminars do
    member do
      patch 'update_attend'
      patch 'update_approval'
      get 'edit_reason'
    end
  end

  resources :activities do
    collection do
      get 'all_meetings'
      get 'my_meetings'
      get 'all_orders'
      get 'my_orders'
    end
  end

  resources :losts do
    collection do
      get 'all_losts'
      get 'my_losts'
    end
  end

  resources :schedules, only: [:index]

  resources :seminars
  resources :sources
  resources :sales_processes
  resources :properties do
    resources :rooms
  end
  resources :losts, only: [:index]
  resources :notifications, only: [:index]
  
  resource :admin, only: [:show] do
    resources :template_models
    resources :hides
    resources :users, :only => [:index, :show]
  end
end

app/models/lead_seminar.rb
class LeadSeminar < ApplicationRecord
  belongs_to :lead
  belongs_to :seminar, optional: true

  # ActiveHash
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :level
  belongs_to :attend
  belongs_to :approval

  with_options presence: true do
    validates :attend_id
    validates :approval_id
  end
  
  with_options allow_blank: true do
    validates :level_id, inclusion: { in: Level.first.id..Level.last.id }
    validates :attend_id, inclusion: { in: Attend.first.id..Attend.last.id }
    validates :approval_id, inclusion: { in: Approval.first.id..Approval.last.id }
  end

  validates :disapproval_reason, presence: true, if: Proc.new { |lead_seminar| lead_seminar.approval_id == 2 }

  validate :seminar?

  private

  def seminar?
    return if seminar_id.blank?
    if Seminar.exists?
      seminar_range = Seminar.first.id..Seminar.last.id
      unless seminar_range.include? seminar_id
        errors.add(:seminar, 'はリストにありません')
        return false
      end
    else
      errors.add(:seminar, 'は対象がありません')
      return false
    end
  end
end

app/controllers/lead_seminars_controller.rb
class LeadSeminarsController < ApplicationController
  before_action :set_lead_seminar, only: [:edit, :update, :update_attend, :update_approval, :edit_reason]

  def create
    @lead = Lead.new(session["lead.regist_data"]["lead"])
    @lead_seminar = @lead.build_lead_seminar(lead_seminar_params)
    respond_to do |format|
      if @lead_seminar.valid?
        @lead.save
        flash[:notice] = 'リードが登録されました'
        session["lead.regist_data"]["lead"].clear
        format.js { render js: "window.location = '#{lead_path(@lead)}'" }
      else
        format.js
      end
    end
  end

  def edit
  end

  def update
    @lead = @lead_seminar.lead
    respond_to do |format|
      if @lead_seminar.update(lead_seminar_params)
        flash[:notice] = 'リードセミナーが更新されました'
        format.js { render js: "window.location = '#{lead_path(@lead)}'" }
      else
        format.js
      end
    end
  end

  def update_attend
    if @lead_seminar.update(lead_seminar_params)
      flash.now[:notice] = '出席が更新されました'
    else
      flash.now[:alert] = '出席が更新されませんでした'
    end
  end

  def edit_reason
  end

  def update_approval
    if @lead_seminar.update(lead_seminar_params)
      flash.now[:notice] = '承認が更新されました'
    else
      flash.now[:alert] = '承認が更新されませんでした'
    end
  end

  private

  def set_lead_seminar
    @lead_seminar = LeadSeminar.find(params[:id])
  end

  def lead_seminar_params
    params.require(:lead_seminar).permit(
      :scheduled_date_time,
      :first_preferred_date_time,
      :second_preferred_date_time,
      :third_preferred_date_time,
      :level_id,
      :attend_reason,
      :experience_investment,
      :interest_investment,
      :question,
      :tracking_id,
      :attend_id,
      :approval_id,
      :disapproval_reason,
      :seminar_id
    )
  end
end

app/helpers/lead_seminars_helper.rb
module LeadSeminarsHelper
end

app/views/lead_seminars/_approval_form.html.erb
<%= form_with model: lead_seminar, url: update_approval_lead_seminar_path(lead_seminar), html: {data: {approval_form: lead_seminar.id}} do |f| %>

  <%= f.collection_select :approval_id, Approval.all, :id, :name, {}, {class: "approval-select", data: {approval_select: lead_seminar.id}} %>

  <%= f.submit "送信", class: "d-none" %>

<% end %>

app/views/lead_seminars/_attend_form.html.erb
<%= form_with model: lead_seminar, url: update_attend_lead_seminar_path(lead_seminar), html: {data: {attend_form: lead_seminar.id}} do |f| %>

  <%= f.collection_select :attend_id, Attend.all, :id, :name, {}, {class: "attend-select", data: {attend_select: lead_seminar.id}} %>

  <%= f.submit "送信", class: "d-none" %>

<% end %>

app/views/lead_seminars/_detail_table.html.erb
<table class="index-table-2">
  <tr>
    <th><span>名前</span></th>
    <th><span>担当者</span></th>
    <th><span>ソース</span></th>
    <th><span>トラッキングID</span></th>
    <th><span>出席</span></th>
    <th><span>承認</span></th>
  </tr>
  <% @lead_seminars.each do |lead_seminar| %>
    <tr>
      <td>
        <%= link_to lead_seminar.lead.name, lead_path(lead_seminar.lead.id) %>
      </td>
      <td>
        <%= lead_seminar.lead.owner&.name %>
      </td>
      <td>
        <%= lead_seminar.lead.source.name %>
      </td>
      <td>
        <%= lead_seminar&.tracking_id %>
      </td>
      <td>
        <%= render partial: 'lead_seminars/attend_form', locals: { lead_seminar: lead_seminar } %>
      </td>
      <td>
        <div data-approval-form-wrap="<%= lead_seminar.id %>">
          <%= render partial: 'lead_seminars/approval_form', locals: { lead_seminar: lead_seminar } %>
        </div>
        <%= link_to "", edit_reason_lead_seminar_path(lead_seminar), data: {approval_link: lead_seminar.id}, remote: true %>
      </td>
    </tr>
  <% end %>
</table>

app/views/lead_seminars/_form.html.erb
<%= form_with model: lead_seminar, html: { class: "overflow-hidden mh-100 d-flex flex-column" } do |f| %>
  <!-- フロー -->
  <% if lead_seminar.new_record? %>
    <div class="w-100 pt-3 px-5 d-flex" style="gap: 12px;">
      <div class="form-flow is-current">
        <span>リード情報の登録</span>
      </div>
      <div class="form-flow is-current">
        <span>セミナー関連情報の登録</span>
      </div>
    </div>
  <% end %>
  <!-- ヘッダー -->
  <div class="modal-header justify-content-center">
    <% if lead_seminar.new_record? %>
      <h4 class="fs-15">セミナー関連情報の登録</h4>
    <% else %>
      <h4 class="fs-15">セミナー関連情報を編集</h4>
    <% end %>
    <button type="button" class="btn-close position-absolute end-0 me-3" data-mdb-dismiss="modal" aria-label="Close"></button>
  </div>
  <!-- ボディー -->
  <div class="modal-body" style="padding-bottom: 100px;">
    <%= render 'layouts/error_messages', model: f.object %>

    <table class="form-table">

      <tr>
        <td>
          <%= f.label :seminar_id, 'セミナー', class: "form-label font-weight-bold" %>
          <% Seminar.exists? ? include_blank_seminar = "---" : include_blank_seminar = "データがありません" %>
          <%= f.collection_select :seminar_id, Seminar.all, :id, :start_date_time, {include_blank: include_blank_seminar}, {class: "form-control"} %>
        </td>
        <td>
          <%= f.label :experience_investment, '投資経験', class: "form-label font-weight-bold" %>
          <%= f.text_field :experience_investment, placeholder: "投資経験", class: "form-control" %>
        </td>
      </tr>

      <tr>
        <td>
          <%= f.label :scheduled_date_time, '予定日時', class: "form-label font-weight-bold" %>
          <%= f.datetime_field :scheduled_date_time, class: "form-control" %>
        </td>
        <td>
          <%= f.label :experience_investment, '興味のある投資', class: "form-label font-weight-bold" %>
          <%= f.text_field :experience_investment, placeholder: "興味のある投資", class: "form-control" %>
        </td>
      </tr>

      <tr>
        <td>
          <%= f.label :first_preferred_date_time, '第１希望日時', class: "form-label font-weight-bold" %>
          <%= f.datetime_field :first_preferred_date_time, class: "form-control" %>
        </td>
        <td>
          <%= f.label :question, '質問', class: "form-label font-weight-bold" %>
          <%= f.text_area :question, placeholder: "質問", class: "form-control mh-100p" %>
        </td>
      </tr>

      <tr>
        <td>
          <%= f.label :second_preferred_date_time, '第２希望日時', class: "form-label font-weight-bold" %>
          <%= f.datetime_field :second_preferred_date_time, class: "form-control" %>
        </td>
        <td>
          <%= f.label :tracking_id, 'トラッキングID', class: "form-label font-weight-bold" %>
          <%= f.text_field :tracking_id, placeholder: "トラッキングID", class: "form-control" %>
        </td>
      </tr>

      <tr>
        <td>
          <%= f.label :third_preferred_date_time, '第３希望日時', class: "form-label font-weight-bold" %>
          <%= f.datetime_field :third_preferred_date_time, class: "form-control" %>
        </td>
        <td>
          <%= f.label :attend_id, '出席', class: "form-label font-weight-bold" %><span class="text-danger">【必須】</span>
          <%= f.collection_select :attend_id, Attend.all, :id, :name, {}, {class: "form-control"} %>
        </td>
      </tr>

      <tr>
        <td>
          <%= f.label :level_id, 'レベル', class: "form-label font-weight-bold" %>
          <%= f.collection_select :level_id, Level.all, :id, :name, {include_blank: "---"}, {class: "form-control"} %>
        </td>
        <td>
          <%= f.label :approval_id, '承認', class: "form-label font-weight-bold" %><span class="text-danger">【必須】</span>
          <%= f.collection_select :approval_id, Approval.all, :id, :name, {include_blank: "---"}, {class: "form-control"} %>
        </td>
      </tr>

      <tr>
        <td>
          <%= f.label :attend_reason, '出席理由', class: "form-label font-weight-bold" %>
          <%= f.text_area :attend_reason, placeholder: "出席理由", class: "form-control mh-100p" %>
        </td>
        <td>
          <%= f.label :disapproval_reason, '不承認理由', class: "form-label font-weight-bold" %>（不承認の場合必須）
          <%= f.text_area :disapproval_reason, placeholder: "不承認理由", class: "form-control mh-100p" %>
        </td>
      </tr>

    </table>
  </div>

  <%# フッター %>
  <div class="modal-footer position-absolute bottom-0 w-100" style="background: rgba(236, 235, 234, 0.9);">
    <button type="button" class="cancel-form btn btn-light" data-mdb-dismiss="modal" data-mdb-ripple-color="dark">閉じる</button>
    <%= f.submit "送信", class: "btn btn-primary" %>
  </div>

<% end %>

app/views/lead_seminars/_reason_form.html.erb
<%= form_with model: lead_seminar, url: update_approval_lead_seminar_path(lead_seminar) do |f| %>

  <!-- ヘッダー -->
  <div class="modal-header">
    <h5>不承認理由</h5>
    <button type="button" class="btn-close" data-mdb-dismiss="modal" aria-label="Close"></button>
  </div>
  <!-- ボディー -->
  <div class="modal-body pt-3 pb-5">
    <%= render 'layouts/error_messages', model: f.object %>

    <%= f.hidden_field :approval_id, :value => 2 %>

    <div>
      <%= f.label :disapproval_reason, '不承認理由' %>
      <%= f.text_area :disapproval_reason, class: "form-control mh-100p" %>
    </div>

  </div>
  <!-- フッター -->
  <div class="modal-footer">
    <button type="button" class="cancel-form btn btn-light" data-mdb-dismiss="modal" data-mdb-ripple-color="dark">閉じる</button>
    <%= f.submit "変更を保存", class: "btn btn-primary" %>
  </div>

<% end %>

app/views/lead_seminars/_show.html.erb
<div class="p-2">
  <div class="p-3 border rounded-3">
    <div class="pb-4 d-flex justify-content-between">
      <h6 class="fs-11" style="border-bottom: dashed 1px #d3d6de;">セミナー関連情報</h6>
      <%= link_to edit_lead_seminar_path(lead_seminar), class: "text-body font-weight-bold", data: {mdb_toggle: "modal", mdb_target: "#leadSeminarModal"}, remote: true do %>
        <i class="fa-solid fa-pen"></i>&ensp;編集
      <% end %>
    </div>
    <!-- ボディー -->
    <div class="d-flex flex-column gap-3">
      
      <div>
        <span class="box-heading pb-2">セミナー</span>
        <span>
          <%= lead_seminar.seminar&.title %>
          <%= l lead_seminar.seminar.start_date_time if lead_seminar.seminar&.start_date_time %>
        </span>
      </div>

      <div>
        <span class="box-heading pb-2">参加予定日</span>
        <span><%= l lead_seminar&.scheduled_date_time if lead_seminar.scheduled_date_time %></span>
      </div>

      <div>
        <span class="box-heading pb-2">参加希望日（第1希望）</span>
        <span><%= l lead_seminar&.first_preferred_date_time if lead_seminar.first_preferred_date_time %></span>
      </div>

      <div>
        <span class="box-heading pb-2">参加希望日（第2希望）</span>
        <span><%= l lead_seminar&.second_preferred_date_time if lead_seminar.second_preferred_date_time %></span>
      </div>

      <div>
        <span class="box-heading pb-2">参加希望日（第3希望）</span>
        <span><%= l lead_seminar&.third_preferred_date_time if lead_seminar.third_preferred_date_time %></span>
      </div>

      <div>
        <span class="box-heading pb-2">レベル</span>
        <span><%= lead_seminar&.level&.name %></span>
      </div>

      <div>
        <span class="box-heading pb-2">参加理由</span>
        <span><%= safe_join(lead_seminar.attend_reason.split("\n"),tag(:br)) if lead_seminar.attend_reason %></span>
      </div>

      <div>
        <span class="box-heading pb-2">投資経験</span>
        <span><%= lead_seminar&.experience_investment %></span>
      </div>

      <div>
        <span class="box-heading pb-2">興味のある投資</span>
        <span><%= lead_seminar&.interest_investment %></span>
      </div>

      <div>
        <span class="box-heading pb-2">質問</span>
        <span><%= safe_join(lead_seminar.question.split("\n"),tag(:br)) if lead_seminar.question %></span>
      </div>

      <div>
        <span class="box-heading pb-2">トラッキングID</span>
        <span><%= lead_seminar&.tracking_id %></span>
      </div>

      <div>
        <span class="box-heading pb-2">出席</span>
        <span><%= lead_seminar.attend.name %></span>
      </div>

      <div>
        <span class="box-heading pb-2">承認</span>
        <span><%= lead_seminar.approval.name %></span>
      </div>

      <div>
        <span class="box-heading pb-2">不承認理由</span>
        <span><%= safe_join(lead_seminar.disapproval_reason.split("\n"),tag(:br)) if lead_seminar.disapproval_reason %></span>
      </div>

    </div>
  </div>
</div>



<!-- モーダル -->
<div class="modal fade" id="leadSeminarModal" tabindex="-1" aria-labelledby="leadSeminarModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-scrollable modal-lg">
    <!-- フォーム -->
    <div id="leadSeminarForm" class="modal-content"></div>
  </div>
</div>

app/views/lead_seminars/create.js.erb
<%# フォームレンダリング %>
$("#leadSeminarForm").html("<%= j(render partial: 'lead_seminars/form', locals: { lead_seminar: @lead_seminar }) %>");

app/views/lead_seminars/edit.js.erb
<%# フォームレンダリング %>
$('#leadSeminarForm').html("<%= j(render 'lead_seminars/form', lead_seminar: @lead_seminar) %>");

app/views/lead_seminars/edit_reason.js.erb
<%# フォームレンダリング %>
$('#reasonFormWrap').html("<%= j(render 'lead_seminars/reason_form', lead_seminar: @lead_seminar) %>");

<%# モーダルを開くボタンをクリック %>
$(`[data-mdb-target="#reasonModal"]`).click();

app/views/lead_seminars/update.js.erb
<%# フォームレンダリング %>
$('#leadSeminarForm').html("<%= j(render 'lead_seminars/form', lead_seminar: @lead_seminar) %>");

app/views/lead_seminars/update_approval.js.erb
<%# エラーの時 %>
<% if @lead_seminar.errors.present? %>
  <%# フォームレンダリング %>
  $('#reasonFormWrap').html("<%= j(render 'lead_seminars/reason_form', lead_seminar: @lead_seminar) %>");

<%# エラーが無い時 %>
<% else %>
  <%# モーダルを閉じる %>
  $('#reasonFormWrap .cancel-form').trigger("click");

  <%# フォームをレンダリング %>
  $(`[data-approval-form-wrap=<%= @lead_seminar.id %>]`).html("<%= j(render 'lead_seminars/approval_form', lead_seminar: @lead_seminar) %>");
<% end %>

<%# フラッシュの表示 %>
$("#flash").html("<%= j(render 'layouts/flash') %>");

app/views/lead_seminars/update_attend.js.erb
<%# フラッシュの表示 %>
$("#flash").html("<%= j(render 'layouts/flash') %>");