config/routes.rb
Rails.application.routes.draw do
  root to: 'home#top'

  devise_for :users, controllers: {
    # registrationsコントローラーを編集できるようにする
    registrations: 'users/registrations'
  }
  devise_scope :user do
    # 管理画面を認識させるため、createはページが存在しないため必要無し
    get 'admin/users/new' => 'users/registrations#new', as: :new_user_admin_registration
    # 管理者用編集パス
    get 'admin/users/:id/edit' => 'users/registrations#edit', as: :edit_other_user_registration
    match 'admin/users/:id', to: 'users/registrations#update', via: [:patch, :put], as: :other_user_registration
  end

  resources :leads do
    collection do
      get 'all_leads'
      get 'my_leads'
      get 'csv'
      post 'csv_import'
    end
    member do
      patch 'update_sales_process'
    end
    resources :activities do
      collection do
        get 'search'
      end
    end
    resources :schedules
    resources :losts
    resources :images
  end

  resources :lead_seminars do
    member do
      patch 'update_attend'
      patch 'update_approval'
      get 'edit_reason'
    end
  end

  resources :activities do
    collection do
      get 'all_meetings'
      get 'my_meetings'
      get 'all_orders'
      get 'my_orders'
    end
  end

  resources :losts do
    collection do
      get 'all_losts'
      get 'my_losts'
    end
  end

  resources :schedules, only: [:index]

  resources :seminars
  resources :sources
  resources :sales_processes
  resources :properties do
    resources :rooms
  end
  resources :losts, only: [:index]
  resources :notifications, only: [:index]
  
  resource :admin, only: [:show] do
    resources :template_models
    resources :hides
    resources :users, :only => [:index, :show]
  end
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :lead
  belongs_to :creator, class_name: 'User'
  belongs_to :attender, class_name: 'User', optional: true
  belongs_to :room, optional: true

  # enum
  enum activity_type: { 行動: 1, 商談: 2, 取引: 3 }, _prefix: true
  enum meeting_type: { 面談: 1, 初訪: 2, 再訪: 3, 買い増し: 4, 紹介依頼: 5 }, _prefix: true

  with_options presence: true do
    validates :activity_type
    validates :overview
    validates :start_date_time
  end

  validates :action_name, presence: true, if: Proc.new { |activity| activity.activity_type == "行動" }
  validates :meeting_type, presence: true, if: Proc.new { |activity| activity.activity_type == "商談" }
  validates :end_date_time, presence: true, if: Proc.new { |activity| activity.activity_type == "商談" }
  validates :meeting_result, presence: true, if: Proc.new { |activity| activity.activity_type == "商談" }
  validates :room, presence: true, if: Proc.new { |activity| activity.activity_type == "取引" }

  scope :not_lost,  -> { left_joins(lead: :lost).where(losts: { lead_id: nil }) }
  scope :not_hide,  -> { left_joins(lead: :hide).where(hides: { lead_id: nil }) }
  scope :only_meeting,  -> { where(activity_type: "商談") }
  scope :only_order,  -> { where(activity_type: "取引") }
  scope :only_creator,  -> (current_user){ where( creator_id: current_user.id ) }
  scope :only_attender,  -> (current_user){ where( attender_id: current_user.id ) }

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:edit, :update, :destroy]
  before_action :set_lead, only: [:new, :create, :edit, :update, :destroy]

  def all_meetings
    @q = Activity.ransack(params[:q])
    # 失注と非表示以外
    @meetings = @q.result.not_lost.not_hide.only_meeting.page(params[:page]).per(50).order(id: "DESC")
    render :meetings
  end

  def my_meetings
    @q = Activity.ransack(params[:q])
    @meetings = @q.result.not_lost.not_hide.only_meeting.only_creator(current_user).or(Activity.not_lost.not_hide.only_order.only_attender(current_user)).page(params[:page]).per(50).order(id: "DESC")
    render :meetings
  end

  def all_orders
    @orders = Activity.not_lost.not_hide.only_order.page(params[:page]).per(50).order(id: "DESC")
    render :orders
  end

  def my_orders
    @orders = Activity.not_lost.not_hide.only_order.only_creator(current_user).or(Activity.not_lost.not_hide.only_order.only_attender(current_user)).page(params[:page]).per(50).order(id: "DESC")
    render :orders
  end

  def new
    @activity = @lead.activities.new
    @form_type = params[:form_type]
  end

  def create
    @form_type = params[:activity][:form_type]
    # enumのパラメータエラーを避けるため例外処理
    begin
      @activity = @lead.activities.new(activity_params)
      @activities = @lead.activities
      if @activity.save
        flash.now[:notice] = '活動が作成されました。'
      else
        flash.now[:alert] = '活動の作成に失敗しました'
      end
    rescue ArgumentError
      @activity = @lead.activities.new
      @activity.errors.add(:base, '不正なパラメーターです')
      flash.now[:alert] = '活動の作成に失敗しました'
    end
  end

  def edit
    @form_type = params[:form_type]
  end

  def update
    @form_type = params[:form_type]
    # enumのパラメータエラーを避けるため例外処理
    begin
      @activities = @lead.activities
      if @activity.update(activity_params)
        flash.now[:notice] = '活動が更新されました'
      else
        flash.now[:alert] = '活動の更新に失敗しました'
      end
    rescue ArgumentError
      @activity.errors.add(:base, '不正なパラメーターです')
      flash.now[:alert] = '活動の更新に失敗しました'
    end
  end

  def destroy
    if @activity.destroy
      @activities = @lead.activities
      flash.now[:notice] = '活動が削除されました'
    else
      flash.now[:alert] = '活動の削除に失敗しました'
    end
  end

  def search
    if params[:keyword] == ""
      actions = []
      render json:{ actions: actions }
    else
      actions = ActionModel.where(['name LIKE ?', "%#{params[:keyword]}%"] )
      render json:{ actions: actions }
    end
  end

  private

  def set_activity
    @activity = Activity.find(params[:id])
  end

  def set_lead
    @lead = Lead.find(params[:lead_id])
  end

  def activity_params
    params.require(:activity).permit(
      :activity_type,
      :action_name,
      :meeting_type,
      :order_type,
      :overview,
      :start_date_time,
      :end_date_time,
      :meeting_result,
      :attender_id,
      :room_id
    ).merge(creator_id: current_user.id)
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_action_form.html.erb
<% if activity.new_record? %>
  <h6 class="pb-2 fs-12 text-center">行動を作成</h6>
<% else %>
  <h6 class="pb-2 fs-12 text-center">行動を編集</h6>
<% end %>

<%= form_with model: [lead, activity], id: "actionForm" do |f| %>

  <div class="py-3 d-flex flex-column gap-3" style="border-top: 1px dashed #d3d6de; border-bottom: 1px dashed #d3d6de;">
    <!-- エラーメッセージ -->
    <%= render 'layouts/error_messages', model: f.object %>

    <%= f.hidden_field :form_type, :value => "action" %>

    <%= f.hidden_field :activity_type, :value => "行動" %>

    <div>
      <%= f.label :action_name, '行動名', class: "form-label font-weight-bold" %><span class="text-danger">【必須】</span>
      <%= f.text_field :action_name, placeholder: "行動名", class: "form-control" %>
    </div>

    <div>
      <%= f.label :start_date_time, '行動日時', class: "form-label font-weight-bold" %><span class="text-danger">【必須】</span>
      <%= f.datetime_field :start_date_time, include_blank: true, class: "form-control w-auto" %>
    </div>

    <div>
      <%= f.label :overview, '概要', class: "form-label font-weight-bold" %><span class="text-danger">【必須】</span>
      <%= f.text_area :overview, placeholder: "概要", class: "form-control mh-100p" %>
    </div>

  </div>
  
  <div class="pt-3 d-flex justify-content-end gap-2">
    <button type="button" class="btn btn-light close-form" data-mdb-ripple-color="dark">閉じる</button>
    <% if activity.new_record? %>
      <%= f.submit "作成", class: "btn btn-primary" %>
    <% else %>
      <%= f.submit "更新", class: "btn btn-primary" %>
    <% end %>
  </div>

<% end %>

app/views/activities/_detail.html.erb
<!-- 行動 -->
<% if activity.activity_type == "行動" %>
  <div class="d-flex">
    <!-- トグルアイコン -->
    <div class="pe-2">
      <i class="toggle-icon fa-solid fa-chevron-right rounded-circle text-hover cursor-pointer text-dark d-flex align-items-center justify-content-center" data-toggle-icon="<%= activity.id %>" style="width: 30px; height: 30px;"></i>
    </div>
    <div class="w-100">
      <!-- ヘッダー -->
      <div class="d-flex justify-content-between align-items-center">
        <!-- 左 -->
        <div>
          <h6><%= activity.action_name.truncate(20) %></h6>
          <span class="fs-7"><%= activity.creator.name %>さんが活動を記録しました</span>
        </div>
        <!-- 右 -->
        <div class="d-flex gap-1">
          <div>
            <span class="fs-7"><%= l activity.created_at %></span>
          </div>
          <!-- ボタン -->
          <div class="dropdown d-flex justify-content-end">
            <button class="bg-transparent border-0" type="button" id="dropdownMenuButton" data-mdb-toggle="dropdown" aria-expanded="false">
              <i class="fa-solid fa-ellipsis-vertical rounded-circle text-hover d-flex align-items-center justify-content-center" style="width: 30px; height: 30px;"></i>
            </button>
            <ul class="dropdown-menu border" aria-labelledby="dropdownMenuButton">
              <li>
                <%= link_to "編集", edit_lead_activity_path(activity.lead, activity, form_type: "action"), remote: true, class: "dropdown-item" %>
              </li>
              <li>
                <%= link_to "削除", lead_activity_path(activity.lead, activity), method: :delete, remote: true, class: "dropdown-item", data: { confirm: '削除しますか？' } %>
              </li>
            </ul>
          </div>
        </div>
      </div>
      <!-- トグルコンテンツ -->
      <div data-toggle-content="<%= activity.id %>", style="display: none;">
        <!-- ボディー -->
        <div class="pt-2 d-flex flex-column gap-1">
          
          <div>
            <span class="font-weight-bold fs-8">行動日時</span>
            <div>
              <span class="fs-9"><%= l activity.start_date_time %></span>
            </div>
          </div>

          <div>
            <span class="font-weight-bold fs-8">概要</span>
            <div class="border rounded-3 p-1">
              <span class="fs-8"><%= safe_join(activity.overview.split("\n"),tag(:br)) %></span>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>

<!-- 商談 -->
<% elsif activity.activity_type == "商談" %>
  <div class="d-flex">
    <!-- トグルアイコン -->
    <div class="ps-2 pe-3">
      <i class="fa-solid fa-chevron-right toggle-icon cursor-pointer text-dark" data-toggle-icon="<%= activity.id %>"></i>
    </div>
    <div class="w-100">
      <!-- ヘッダー -->
      <div class="d-flex justify-content-between align-items-center">
        <!-- 左 -->
        <div>
          <div class="d-flex align-items-center">
            <h6><%= activity.meeting_type %></h6>（結果：<%= activity.meeting_result.truncate(15) %>）
          </div>
          <span class="fs-7"><%= activity.creator.name %>さんが活動を記録しました</span>
        </div>
        <!-- 右 -->
        <div class="d-flex gap-1">
          <div>
            <span class="fs-7"><%= l activity.created_at %></span>
          </div>
          <!-- ボタン -->
          <div class="dropdown d-flex justify-content-end">
            <button class="bg-transparent border-0" type="button" id="dropdownMenuButton" data-mdb-toggle="dropdown" aria-expanded="false">
              <i class="fa-solid fa-ellipsis-vertical rounded-circle text-hover d-flex align-items-center justify-content-center" style="width: 30px; height: 30px;"></i>
            </button>
            <ul class="dropdown-menu border" aria-labelledby="dropdownMenuButton">
              <li>
                <%= link_to "編集", edit_lead_activity_path(activity.lead, activity, form_type: "meeting"), remote: true, class: "dropdown-item" %>
              </li>
              <li>
                <%= link_to "削除", lead_activity_path(activity.lead, activity), method: :delete, remote: true, class: "dropdown-item", data: { confirm: '削除しますか？' } %>
              </li>
            </ul>
          </div>
        </div>
      </div>
      <!-- トグルコンテンツ -->
      <div data-toggle-content="<%= activity.id %>", style="display: none;">
        <!-- ボディー -->
        <div class="pt-2 d-flex flex-column gap-1">

          <div class="d-flex">
            <div class="w-50">
              <span class="font-weight-bold fs-8">商談開始日時</span>
              <div>
                <span class="fs-9"><%= l activity.start_date_time %></span>
              </div>
            </div>
          
            <div>
              <span class="font-weight-bold fs-8">商談終了日時</span>
              <div>
                <span class="fs-9"><%= l activity.end_date_time %></span>
              </div>
            </div>
          </div>

          <div>
            <span class="font-weight-bold fs-8">同席者</span>
            <div>
              <span class="fs-9"><%= activity.attender&.name %></span>
            </div>
          </div>

          <div>
            <span class="font-weight-bold fs-8">概要</span>
            <div class="border rounded-3 p-1">
              <span class="fs-8"><%= safe_join(activity.overview.split("\n"),tag(:br)) %></span>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>

<!-- 取引 -->
<% elsif activity.activity_type == "取引" %>
  <div class="d-flex">
    <!-- トグルアイコン -->
    <div class="ps-2 pe-3">
      <i class="fa-solid fa-chevron-right toggle-icon cursor-pointer text-dark" data-toggle-icon="<%= activity.id %>"></i>
    </div>
    <div class="w-100">
      <!-- ヘッダー -->
      <div class="d-flex justify-content-between align-items-center">
        <!-- 左 -->
        <div>
          <h6 class="fs-9">契約</h6>
          <span class="fs-7"><%= activity.creator.name %>さんが活動を記録しました</span>
        </div>
        <!-- 右 -->
        <div class="d-flex gap-1">
          <div>
            <span class="fs-7"><%= l activity.created_at %></span>
          </div>
          <!-- ボタン -->
          <div class="dropdown d-flex justify-content-end">
            <button class="bg-transparent border-0" type="button" id="dropdownMenuButton" data-mdb-toggle="dropdown" aria-expanded="false">
              <i class="fa-solid fa-ellipsis-vertical rounded-circle text-hover d-flex align-items-center justify-content-center" style="width: 30px; height: 30px;"></i>
            </button>
            <ul class="dropdown-menu border" aria-labelledby="dropdownMenuButton">
              <li>
                <%= link_to "編集", edit_lead_activity_path(activity.lead, activity, form_type: "order"), remote: true, class: "dropdown-item" %>
              </li>
              <li>
                <%= link_to "削除", lead_activity_path(activity.lead, activity), method: :delete, remote: true, class: "dropdown-item", data: { confirm: '削除しますか？' } %>
              </li>
            </ul>
          </div>
        </div>
      </div>
      <!-- トグルコンテンツ -->
      <div data-toggle-content="<%= activity.id %>", style="display: none;">
        <!-- ボディー -->
        <div class="pt-2 d-flex flex-column gap-1">

          <div>
            <span class="font-weight-bold fs-8">契約日時</span>
            <div>
              <span class="fs-9"><%= l activity.start_date_time %></span>
            </div>
          </div>

          <div class="d-flex">
            <div class="w-50">
              <span class="font-weight-bold fs-8">同席者</span>
              <div>
                <span class="fs-9"><%= activity.attender&.name %></span>
              </div>
            </div>

            <div>
              <span class="font-weight-bold fs-8">物件</span>
              <div>
                <span class="fs-9"><%= link_to activity.room.property.name + ' (' + activity.room.number.to_s + '号室)', property_path(activity.room.property), class: "text-link" %></span>
              </div>
            </div>
          </div>

          <div>
            <span class="font-weight-bold fs-8">概要</span>
            <div class="border rounded-3 p-1">
              <span class="fs-8"><%= safe_join(activity.overview.split("\n"),tag(:br)) %></span>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/activities/_meeting_form.html.erb
<% if activity.new_record? %>
  <h6 class="pb-2 fs-12 text-center">商談を作成</h6>
<% else %>
  <h6 class="pb-2 fs-12 text-center">商談を編集</h6>
<% end %>

<%= form_with model: [lead, activity], id: "meetingForm" do |f| %>
  <div class="py-3 d-flex flex-column gap-3" style="border-top: 1px dashed #d3d6de; border-bottom: 1px dashed #d3d6de;">
    <%# エラーメッセージ %>
    <%= render 'layouts/error_messages', model: f.object %>

    <%= f.hidden_field :form_type, :value => "meeting" %>

    <%= f.hidden_field :activity_type, :value => "商談" %>

    <div>
      <%= f.label :meeting_type, '商談タイプ', class: "form-label font-weight-bold" %><span class="text-danger">【必須】</span>
      <%= f.collection_radio_buttons :meeting_type, Activity.meeting_types, :first , :first do |b| %>
        <div class="form-check">
          <%= b.label(class: "form-check-label") { b.radio_button(class: "form-check-input") + b.text } %>
        </div>
      <% end %>
    </div>

    <div>
      <%= f.label :start_date_time, '開始日時', class: "form-label font-weight-bold" %><span class="text-danger">【必須】</span>
      <%= f.datetime_field :start_date_time, include_blank: true, class: "form-control w-auto" %>
    </div>

    <div>
      <%= f.label :end_date_time, '終了日時', class: "form-label font-weight-bold" %><span class="text-danger">【必須】</span>
      <%= f.datetime_field :end_date_time, include_blank: true, class: "form-control w-auto" %>
    </div>

    <div>
      <%= f.label :attendee_id, '同席者', class: "form-label font-weight-bold" %>
      <%= f.collection_select :attender_id, User.all, :id, :name, {include_blank: "---"}, {class: "form-control w-auto"} %>
    </div>

    <div>
      <%= f.label :meeting_result, '商談結果', class: "form-label font-weight-bold" %><span class="text-danger">【必須】</span>
      <%= f.text_field :meeting_result, placeholder: "商談結果", class: "form-control" %>
    </div>

    <div>
      <%= f.label :overview, '概要', class: "form-label font-weight-bold" %><span class="text-danger">【必須】</span>
      <%= f.text_area :overview, placeholder: "概要", class: "form-control mh-300p" %>
    </div>

    <div>
      <% if activity.new_record? %>
        <% templates = TemplateModel.all %>
        <% templates.each do |template| %>
          <div>
            <input type="hidden" value="<%= template.template_text %>">
            <input type="checkbox" class="checkbox" id="checkbox-<%= template.id %>">
            <label for="checkbox-<%= template.id %>">テンプレート<%= template.id %>（<%= template.template_type %>）を使用</label>
          </div>
        <% end %>
      <% end %>
    </div>

  </div>

  <div class="pt-3 d-flex justify-content-end gap-2">
    <button type="button" class="btn btn-light close-form" data-mdb-ripple-color="dark">閉じる</button>
    <% if activity.new_record? %>
      <%= f.submit "作成", class: "btn btn-primary" %>
    <% else %>
      <%= f.submit "更新", class: "btn btn-primary" %>
    <% end %>
  </div>

<% end %>

app/views/activities/_meeting_index_table.html.erb
<table class="index-table-2">
  <tr>
    <th>
      リード名
    </th>
    <th>
      商談タイプ
    </th>
    <th>
      開始日時
    </th>
    <th>
      終了日時
    </th>
    <th>
      作成者
    </th>
    <th>
      同席者
    </th>
    <th>
      概要
    </th>
  </tr>
  <% @meetings.each do |meeting| %>
    <tr>
      <td>
        <%= link_to meeting.lead.name, lead_path(meeting.lead) %>
      </td>
      <td>
        <%= meeting.meeting_type %>
      </td>
      <td>
        <%= l meeting.start_date_time %>
      </td>
      <td>
        <%= l meeting.end_date_time %>
      </td>
      <td>
        <%= meeting.creator.name %>
      </td>
      <td>
        <%= meeting.attender&.name %>
      </td>
      <td>
        <%= meeting.overview.truncate(20) %>
      </td>
    </tr>
  <% end %>
</table>

app/views/activities/_no_activity.html.erb
<% if activities.empty? %>
  活動がありません
<% end %>

app/views/activities/_order_index_table.html.erb
<table class="index-table-2">
  <tr>
    <th>リード名</th>
    <th>開始日時</th>
    <th>物件</th>
    <th>作成者</th>
    <th>同席者</th>
    <th>概要</th>
  </tr>
  <% @orders.each do |order| %>
    <tr>
      <td>
        <%= link_to order.lead.name, lead_path(order.lead) %>
      </td>
      <td>
        <%= l order.start_date_time %>
      </td>
      <td>
        <%= link_to order.room.property.name + ' (' + order.room.number.to_s + '号室)', property_path(order.room.property) %>
      </td>
      <td>
        <%= order.creator.name %>
      </td>
      <td>
        <%= order.attender&.name %>
      </td>
      <td>
        <%= order.overview.truncate(30) %>
      </td>
    </tr>
  <% end %>
</table>

app/views/activities/_tab.html.erb
<!-- 作成ボタン -->
<div class="p-2">
  <div class="btn-group" role="group">
    <%= link_to "新規行動", new_lead_activity_path(lead, form_type: "action"), remote: true, class: "btn btn-primary" %>
    <%= link_to "新規商談", new_lead_activity_path(lead, form_type: "meeting"), remote: true, class: "btn btn-primary" %>
    <%= link_to "新規契約", new_lead_activity_path(lead, form_type: "order"), remote: true, class: "btn btn-primary" %>
  </div>
</div>

<div class="p-2 d-flex flex-column gap-4">
  <!-- 行動フォーム -->
  <div id="actionFormWrap" class="form-wrap p-3 border rounded-3" style="display: none;">
  </div>
  <!-- 商談フォーム -->
  <div id="meetingFormWrap" class="form-wrap p-3 border rounded-3" style="display: none;">
  </div>
  <!-- 取引フォーム -->
  <div id="orderFormWrap" class="form-wrap p-3 border rounded-3" style="display: none;">
  </div>
  <div id="activities" class="d-flex flex-column gap-1">
    <% activities.each do |activity|%>
      <%= render partial: 'activities/show', locals: { activity: activity } %>
    <% end %>
    <div id="noActivity" class="py-5 text-center">
      <%= render partial: 'activities/no_activity', locals: { activities: activities } %>
    </div>
  </div>
</div>

app/views/activities/destroy.js.erb
<%# 要素を削除 %>
$(`[data-activity=<%= @activity.id %>]`).fadeOut('fast').queue(function() {
  $(`[data-activity=<%= @activity.id %>]`).remove();
});

<%# フォームが開いていてインスタンスが同じならフォームを閉じる %>
if ($('#actionFormWrap').css('display') == 'block') {
  let action = $('#actionFormWrap form').attr('action');
  let path = "<%= lead_activity_path(@lead, @activity) %>";
  if(action == path) {
    $(".form-wrap").hide();
  }
} else if ($('#meetingFormWrap').css('display') == 'block') {
  let action = $('#meetingFormWrap form').attr('action');
  let path = "<%= lead_activity_path(@lead, @activity) %>";
  if(action == path) {
    $(".form-wrap").hide();
  }
} else if ($('#orderFormWrap').css('display') == 'block') {
  let action = $('#orderFormWrap form').attr('action');
  let path = "<%= lead_activity_path(@lead, @activity) %>";
  if(action == path) {
    $(".form-wrap").hide();
  }
}

<%# noActivityをレンダリング %>
$("#noActivity").html("<%= j(render partial: 'activities/no_activity', locals: { activities: @activities }) %>");

<%# フラッシュの表示 %>
$("#flash").html("<%= j(render 'layouts/flash') %>");

app/views/activities/meetings.html.erb
<main>
  <div class="content-wrap content-wrap--table content-wrap--height">
    <div>
      <!-- ヘッダー -->
      <div class="p-3 d-flex justify-content-between">
        <!-- 左 -->
        <div class="d-flex flex-column justify-content-between gap-4">
          <!-- 上段 -->
          <div class="main-heading">
            <i class="fa-solid fa-briefcase fa-lg main-heading--box"></i>
            <h6 class="main-heading--title">商談</h6>
          </div>
          <!-- 下段 -->
          <div class="d-flex justify-content-between">
            <div class="tab">
              <% if request.path.include?('/all_meetings') %>
                <span class="tab__item is-active">全ての商談</span>
                <%= link_to "自分の商談", my_meetings_activities_path, class: "tab__item"%>
              <% elsif request.path.include?('/my_meetings') %>
                <% unless current_user.role == "一般" %>
                  <%= link_to "全ての商談", all_meetings_activities_path, class: "tab__item"%>
                <% end %>
                <span class="tab__item is-active">自分の商談</span>
              <% end %>
            </div>
          </div>
        </div>
        <!-- 右 -->
        <div class="d-flex flex-column justify-content-between">
          <!-- 上段 -->
          <div class="d-flex gap-1">
          </div>
          <!-- 下段 -->
          <div class="d-flex justify-content-end gap-2">
            <%= render partial: 'search_meeting_type_form', locals: { q: @q } %>
          </div>
        </div>
      </div>
      <!-- テーブル -->
      <div class="table-wrapper">
        <%= render partial: 'meeting_index_table', locals: { meetings: @meetings } %>
      </div>
    </div>
    <!-- ページネーション -->
    <div class="py-5">
      <%= paginate @meetings %>
    </div>
  </div>
</main>

app/views/activities/orders.html.erb
<main>
  <div class="content-wrap content-wrap--table content-wrap--height">
    <div>
      <!-- ヘッダー -->
      <div class="p-3 d-flex justify-content-between">
        <!-- 左 -->
        <div class="d-flex flex-column justify-content-between gap-4">
          <!-- 上段 -->
          <div class="main-heading">
            <i class="fa-solid fa-handshake fa-lg main-heading--box"></i>
            <h6 class="main-heading--title">取引</h6>
          </div>
          <!-- 下段 -->
          <div class="d-flex justify-content-between">
            <div class="tab">
              <% if request.path.include?('/all_orders') %>
                <span class="tab__item is-active">全ての取引</span>
                <%= link_to "自分の取引", my_orders_activities_path, class: "tab__item"%>
              <% elsif request.path.include?('/my_orders') %>
                <% unless current_user.role == "一般" %>
                  <%= link_to "全ての取引", all_orders_activities_path, class: "tab__item"%>
                <% end %>
                <span class="tab__item is-active">自分の取引</span>
              <% end %>
            </div>
          </div>
        </div>
        <!-- 右 -->
        <div class="d-flex flex-column justify-content-between">
          <!-- 上段 -->
          <div class="d-flex gap-1">
          </div>
          <!-- 下段 -->
          <div class="d-flex justify-content-end gap-2">
          </div>
        </div>
      </div>
      <!-- テーブル -->
      <div class="table-wrapper">
        <%= render partial: 'order_index_table', locals: { orders: @orders } %>
      </div>
    </div>
    <!-- ページネーション -->
    <div class="py-5">
      <%= paginate @orders %>
    </div>
  </div>
</main>